import { IBM_Plex_Mono } from "next/font/google";
import "../globals.css";
import SidebarMenu from "../Sidebarmenu";

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: "500",
  variable: "--font-ibm-plex-mono",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className="">
        <SidebarMenu/>
      {children}
    </div>
  );
}

